### ISSUE TITLE
Java Implementation seems to be a bit gimped

### ISSUE THREAD

**Issue by ciplogic** [ExaScience/elprep-bench#2]
Hi Pascal,

I had kind of little time to fully evaluate the Java implementation, but I assume that it wasn't intentional but I noticed even very small performance mistakes that change a lot the runtime performance (I don't know how to track the GC usage, but it should also be less).

I will show 3 problems but I noticed fewer more.

Slice has many conflicts with hashes, so changing like this (no GC impact, just speedup) the hash function it is (at least with the smallest sample) a visible impact:

```
  public int hashCode () {
    var result = 13;
    for (var i = pos; i < pos+length; ++i) {
      result = 73*result + storage.charAt(i);
    }
    return result;
  }
```

Another bigish item is when you write outside, you create a lot of small objects which force GC to happen.

So changing the output printer buffer to have some preallocated size (2K seems just right), I get on writing output more than 10% speedup (and it should generate much less GC):
```     var outputStream = alnStream.parallel().map((aln) -> {
// here is preallocated, in original there was no 2000 value   
                 var sw = new StringWriter(2000);
                    try (var swout = new PrintWriter(sw)) {
                        aln.format(swout);
                    }
                    return sw.toString();
                });
```

Another place is that when parsing integers and in general SAM files, you generate tons of garbage which has an impact on GC. Just changing "doInt" (if I recall right) with a simple integer parsing that doesn't do allocations will speedup up by default on reading part with more than 10%.

**Comment by ciplogic** [comment]
I want to add a clarification, just if it is not clear: I don't assume the writer did the code wrong because it just wanted to write it slower (I assume that Pascal wrote it). Just that probably you didn't spent time profiling it on the time you saved by implementing it in Java in the first place.

I noticed some other mistakes like not using: `Character.isDigit` but instead implementing your own version (inside `CigarOperation.isDigit`) which though it is broken:
```
  public static boolean isDigit (char c) {
    return (('0' <= c) && (c <= '9'));
  }
```

I am not sure if this 10% is a variation on my machine though or on GC options I have so probably

**Comment by ciplogic** [comment]
I will probably get a more extended analysis after I finish it. Otherwise it would be a distraction for everyone.

The single part I noticed is simply that at least around 10% of performance (on my machine) can be achieved with simple tweaks. Not sure though if it matters in the grand scheme of things as I tested it with the smallest BAM file. Probably I should use at least a 1 GB input file to get better numbers.

**Comment by ghost** [comment]
Thanks a lot for taking your time to do this sort of analysis. However, the main issue of the Java version is not so much the runtime performance - it already fares pretty well in that regard. The main issue is the memory use, which would need to be dramatically reduced to be competitive.

**Comment by ciplogic** [comment]
This is no problem to check it.

I can say what I found, and again, these numbers may matter especially as it looks that you use "String" everywhere but wrapped as "Slice" and I compared with Go's String implementation which the type of data is a byte[]. 

So let's start with what I have now:
Your original implementation is this for the biggest SAM file I can process (it is a 120 MB BAM -> converted to SAM file)
Your time is:
```Reading SAM into memory and applying filters.
Elapsed time: 3296 ms.
Write to file.
Elapsed time: 3866 ms.
```
and my tuned implementation (I didn't change the hash implementation but small tunnings) I could extract I would extract around 10% performance.

```
Reading SAM into memory and applying filters.
Elapsed time: 3410 ms.
Write to file.
Elapsed time: 2963 ms.
```
(tests done on Windows 10 64, Ryzen 7 1700 8x2 threads, 32 GB, default Zulu OpenJDK 11 install 64 bit)

The time is too short to say it would improve your 10 minutes like runtimes as you mentioned as I don't have access to a high amount of memory machine, but even the mapping looks and is slower initially, it removes few parts on the GC cost so if the GC would happen more frequent (which I assume it would) the performance will delta could be a bit higher.

Running Java into a profiler (I used the trial of YourKit) shows that most of time the code is spent formatting strings, which makes me asking that maybe this is a reason why Java could be sped up more: Slice could use directly the underlying byte array instead of a String, and it could help all the things involved: the GC (as it has to visit one level less of objects) and the formatting back and forth on the reading/writing from disk. 

Even the smallest string is 24 bytes but the most important is not only the size, but that every time a GC would happen, the millions scale of your algorithm. In the smallest BAM file we talk about 2 million SAMAllignment instances and they have 6 strings each and being byte arrays would save 12 x 24 millions of objects which need not to be visited = 288 million objects.

And if you ask yourself: how could I debug having a byte array to a Slice? Implementing 'toString' to give back the string implementation of the ASCII byte array should suffice.

I don't know too much the genetics domain, but also, just changing `aln.RNAME` and `aln.QNAME` would show if this is a save or not. 

Size of 24 bytes I am taking it from here:
https://www.baeldung.com/java-size-of-object

**Comment by ciplogic** [comment]
I found a way to exclude outliers (as Java requires warm-up) by changing the original loop:
```
 else if (args[0].equals("filter")) {
                elPrepFilterScript(args);
                timedRun(true, "Run all repeated.", () -> {
                    for (int i = 0; i < 10; i++) {
                        elPrepFilterScript(args);
                    }
                });
}
```


With your original implementation it fluctuates at 8.5 GB memory usage:
```
Elapsed time: 55130 ms.
```

With the tuned implementation: memory usage fluctuates around 9.1 GB mark (not sure why it uses more memory)
```
Elapsed time: 50915 ms.
```

I will close the bug as I would assume there is no interest to rewrite/tune a Java version. Would it be interesting to use other languages? (I am thinking about .Net Core!?), would it have any use (maybe a last position to a paper as an implementor)?

**Comment by ciplogic** [comment]
I rewrote the data structures to use what I was suggesting yesterday and I tested the code on Linux (so I am using an equivalent "byte[]" on Java in Slice class which is equivalent with Go's string representation.

I also tested it on Linux (the single Linux machine is an mobile CPU quad-core with 16 GB of RAM, which it is kinda half of CPU compute resources from the yesterday's system) and the improvements are really more dramatic:

So instead of tunning array sizes and buffers, the Slice class basically keeps internally instead of a "String store" it will keep a "byte[] store" and I will rewrite the "format" methods which before were using strings to use "byte[]" obviously.

```Original:
Elapsed time: 94173 ms. 

Optimized:
Elapsed time: 73635 ms.
```
Which is a speedup of 27.89%

Would it worth to discuss that difference in implementation?

**Comment by ciplogic** [comment]
I could speedup the implementation to 34% on Window and to 37% on Linux (with no VM tunning, no change in semantic on the algorithm level) and this would make Java the best in your paper scoring.

Can you guide me to a channel to publish a criticism paper on Java implementation only?

The single caveat I could see is that the performance speedup is higher on my quad core machine (around 37%) vs 8 core machine (around 34.5-35%), which could mean than is possible that the final speedup to be lower on very high core count machine you are working with (but machines are so different like Windows vs Linux, AMD vs Intel, 32 GB DDR4 vs 16 GB DDR3)

If needed, I can send to you the draft privately, if you want more details email me at ciprian.mustiata at gmail.com

**Comment by ghost** [comment]
Thanks a lot for your interest in doing these experiments. Please keep in mind that our main goal was not to publish a paper, but to evaluate different programming languages and decide on a particular one to continue our development of elPrep in. The paper is just an additional outcome of our experiment, because we thought it might be interesting for others to read about our experiences and insights.

A benchmark that compares performance only on comparatively small machines is, frankly speaking, not interesting to us because the data sets we are dealing with in real-world uses of elPrep are significantly higher. Another issue is that, since the benchmarks described in our paper, we also added more optimizations to the Go code, which by now also performs better and uses less memory than the version described in the paper. So a new evaluation would have to also consider additional optimizations in all three programming languages, not just one.

I am not aware if there is a journal that would publish a criticism paper based on your Java implementation only. Finding good publication channels, and writing articles in a style that makes them acceptable to such journals is one of the hardest parts of doing and publishing research. We hope that you are successful in finding such a journal, and feel free to let us know when your article is published.

**Comment by ciplogic** [comment]
You are right, but at the moment of writing the paper, it looks that the paper showed a Java implementation that could process up-to 40% less data per unit of time (at least on small machines) which would make the conclusion of the original paper faulty, even the scaling would be different for large machines, it would not be a 30% better score, but it would be like 5-10%. 

The criticism of this issue was just that: C++ was optimized - you were mentioning that you cared to not make too many copies that C++ does - (you stated this on Reddit, where I found this paper originally), and for Java you tuned the algorithm of GC, but not the implementation of Java code.
